"""unique recipe.title

Revision ID: 124ecb23ab1c
Revises: d06b65b44f6e
Create Date: 2025-12-03 17:10:06.236190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124ecb23ab1c'
down_revision: Union[str, Sequence[str], None] = 'd06b65b44f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipes', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='unique')
    # ### end Alembic commands ###
