"""unique on recipe.normalized_title

Revision ID: 3ba7e9dd2856
Revises: 124ecb23ab1c
Create Date: 2025-12-03 17:26:30.883743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba7e9dd2856'
down_revision: Union[str, Sequence[str], None] = '124ecb23ab1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('normalized_title', sa.String(), nullable=False))
    op.drop_constraint(op.f('recipes_title_key'), 'recipes', type_='unique')
    op.create_index('ix_recipe_normalized_title', 'recipes', ['normalized_title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_normalized_title', table_name='recipes')
    op.create_unique_constraint(op.f('recipes_title_key'), 'recipes', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('recipes', 'normalized_title')
    # ### end Alembic commands ###
