/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          container: 'var(--primary-container)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
          container: 'var(--secondary-container)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          'container-lowest': 'var(--surface-container-lowest)',
          'container-low': 'var(--surface-container-low)',
          container: 'var(--surface-container)',
          'container-high': 'var(--surface-container-high)',
          'container-highest': 'var(--surface-container-highest)',
          variant: 'var(--surface-variant)',
        },
        outline: {
          DEFAULT: 'var(--outline)',
          variant: 'var(--outline-variant)',
        },
        tertiary: {
          DEFAULT: 'var(--tertiary)',
          container: 'var(--tertiary-container)',
        },
        'on-primary': 'var(--primary-foreground)',
        'on-surface': 'var(--foreground)',
        'on-surface-variant': 'var(--muted-foreground)',
        'on-primary-container': 'var(--on-primary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',
        'inverse-surface': 'var(--inverse-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-tint': 'var(--surface-tint)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'primary-fixed': {
          DEFAULT: 'var(--primary-fixed)',
          dim: 'var(--primary-fixed-dim)',
        },
        'on-primary-fixed': {
          DEFAULT: 'var(--on-primary-fixed)',
          variant: 'var(--on-primary-fixed-variant)',
        },
        'secondary-fixed': {
          DEFAULT: 'var(--secondary-fixed)',
          dim: 'var(--secondary-fixed-dim)',
        },
        'on-secondary-fixed': {
          DEFAULT: 'var(--on-secondary-fixed)',
          variant: 'var(--on-secondary-fixed-variant)',
        },
        'tertiary-fixed': {
          DEFAULT: 'var(--tertiary-fixed)',
          dim: 'var(--tertiary-fixed-dim)',
        },
        'on-tertiary-fixed': {
          DEFAULT: 'var(--on-tertiary-fixed)',
          variant: 'var(--on-tertiary-fixed-variant)',
        },
        nutri: {
          a: 'var(--nutri-a)',
          b: 'var(--nutri-b)',
          c: 'var(--nutri-c)',
          d: 'var(--nutri-d)',
          e: 'var(--nutri-e)',
        },
      },
      spacing: {
        'stack-sm': '16px',
        'stack-md': '32px',
        'stack-lg': '64px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'gutter': '32px',
        'section-gap': '128px',
        'container-max': '1280px',
      },
      fontFamily: {
        heading: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-md': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
