"""initial tables

Revision ID: 098e45fde429
Revises: 
Create Date: 2025-12-23 11:49:03.729764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098e45fde429'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('net_quantity_value', sa.Float(), nullable=True),
    sa.Column('net_quantity_unit', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_normalized_name', 'catalog', ['normalized_name'], unique=False)
    op.create_index('ix_catalog_product_url', 'catalog', ['product_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_product_url', table_name='catalog')
    op.drop_index('ix_catalog_normalized_name', table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
