"""add_llm_enrichment_fields

Revision ID: 19f2be905e1d
Revises: 829f0141d9f0
Create Date: 2026-05-14 14:32:57.785328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19f2be905e1d"
down_revision: str | Sequence[str] | None = "829f0141d9f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("catalog", sa.Column("price", sa.Float(), nullable=True))
    op.add_column("catalog", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("catalog", sa.Column("category", sa.String(), nullable=True))
    op.add_column(
        "catalog", sa.Column("nutrition", postgresql.JSON(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog", "nutrition")
    op.drop_column("catalog", "category")
    op.drop_column("catalog", "currency")
    op.drop_column("catalog", "price")
    # ### end Alembic commands ###
