"""is_food column

Revision ID: 829f0141d9f0
Revises: 098e45fde429
Create Date: 2026-02-05 05:52:16.373884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "829f0141d9f0"
down_revision: str | Sequence[str] | None = "098e45fde429"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("catalog", sa.Column("is_food", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog", "is_food")
    # ### end Alembic commands ###
