---
# ============================================================
# Crawler (scheduled CronJob)
# ============================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: macmac-crawler
  namespace: macmac
spec:
  schedule: "0 20 * * 3"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: crawler
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: macmac-pull-secret
          volumes:
            - name: cfg
              configMap:
                name: macmac-config
          containers:
            - name: crawler
              image: quay.io/caugello/macmac-crawler:v0.2.6
              imagePullPolicy: Always
              volumeMounts:
                - name: cfg
                  mountPath: /opt/app-root/src/config.yaml
                  subPath: config.yaml
              env:
                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: macmac-app-secret
                      key: RABBITMQ_USER
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: macmac-app-secret
                      key: RABBITMQ_PASSWORD
                - name: RABBITMQ_URL
                  value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672/%2F"
              command:
                - python
                - -m
                - services.catalog.crawler.main
